---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: opslora-test-ns
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCg8NUq8/PKasz7WunAxx/OLHzsUPnkfWwUK0x34oKeUrPvcBYH5iStjV6YSy5QIq3sOVM9tE0gzIzB/XzIYNb//jH35qXPoNsA+09JG2MN0i101+WGBtichDVjqJnJ43anczsv/aZjVWd+OdGdlAQ7vV0ZoE9E2NwQCiJm9QM8jmeqLsuqmHuNRlnAL0u0z6AA28PMAclXqRrUy+pIiyWnYXo3tbZ6xRkRVzHq45mPSFgcQ411hUN2hCIRMtMSKFXp4MuJDVzsL6ROgZxwZNO2TcjL8JrBRupJ4ub2uJ+b1gJPMfyxPUuKVWts9SYiKsR8nPQLWl4k+1CN1R3cwQdHZy2wH/+HCQZS8U+m8MNplR69x05veIf/y+3ayV7ZevO+R1Stb8riacyamzuUPgQdtJWQPopMdynr+D65DR/zpZzWFp9t2oCmRxBPlL5WlJ6y1fdLirOZE/ghX3TaMJ+PHcxiiNUB7aKPzJARE2zdmoh3QNfID6AAZn7d2jzAFrZgVXJe8HsymIuTDr0TdtYad3qIV14zycGaAsQiWoHDRp4y5/2CH6GV8V8rwV6ayTM1FLTLXTJy1VvLLd+zC7DRTb3Y1KhrkeQO2PNHHFXey3sV/J4yVWzANmW6EejZy1xVezI4SCbrbZVCuK8eauTkukUSqCQGFkbf3Mwhq3SJCAbcgZWRaskfT1SX0EoG/ENL2Pa/fFJ9xCg6Y+qB
    RABBITMQ_DEFAULT_USER: AgBL1diG5xFOo56R4EAsZ2f3+/0bc0/IbVmTUoDkIXRUjhxYY7iuqYtpVqvG01M57O78guTwd4bbG9VJasX1UwVAaXfuhLa5r1zghW3pCy0GSNNm9ORnkjh5lEllhLku9fTFp/OJhSDX+FJxn7r1eQvaPFKSklyJjr+C9I4UwWErL1TXRn5P+D/x8NDP1kWL1y/LPidK6eyIuiTD3cxYzzphniDjsM4qL+YJREoNySd/cGiMl5GPuMDa4IBd4rZBwRvH+VeuuGK/IW0dHH8bZ4MQ6bjAc6JbyIJh7FgPyYdGMKCGvLIixR7BHeOCQM0fDU9oeR/ufv+Dah3WN5Rx5qytfoEUUqZtiCbS8ByTjWCWIrb2sUb+/zsLGZrpCmdg3C778d3GRdM/qOGMGSD71XtlhJ1e6JgJxt3PiJFNITYC2e8KWgiiogbcq6p5tPNgQ6umfxTeoYio5UJQyL6tYuAyvK7xAzbZ+VXbd6j2uYH06SWU1gs5swQm30hlcZcxxU6et2v22gOeX6HfSVa9bvERX9WzcsJrg/EVMWYYbitFsSGet32Vg5+JpTHKGx4cPqI/bFEL61z8NXSIQCN6YUvDTd/FlFZ9vuYnnbSqcOxJ63b+kwfx07iteZXE3mqKykT/W0mToUKfvx+pRft/RUQKIf3RCVMm8nkIukfynhRMqvnxdu30A8xiGU6Rlt/1Dqry45Cxp60IO4g=
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: opslora-test-ns
    type: Opaque
