---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: opslora-app-ns
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCQ/fZT4/c73RyDVaz8JRZ0RdEfw4zqp3ns87RS/gRzzndc+IKWMHbpIR2TU5tIkTQLhtGhWD3gNsNvwTV1pqCFbFCmNzXrwgu4NjjTGgEJCuUdqkZH7S+kZqWJDT5HFvUrcgBZldUs19vgCZTWOfKRoj6fVY+avZHI7WBPRc4n6EP3g7xz9+gJ10F641Di11FK4P63sK8jJ8/K0d8cFRZthn/TMFrx3O4evob+iQSWMit7PZNkd57yFK15TdBhwVYc5m97W7ogUMqrKoGw8/h25MR1ylMQUjVp8Zf/xIwLsmMqQIXfm0fTyGwB6S7HQjHQmXJjP30WEUmEOwXKjDVq0bhfWdotvMOy8jCtRTjzun/qKDkncZQVmI9rSJ24p3ef/SLLOnE0RMikHAYmnyJsPdBghVHy4S5e16fO0nkykv4Ii55c2fUgtk/ytEpzvgk2gWJFDfWgWwxpuKX9au6XNrNUuU/qJRgptsfm6cBby+VWC31HrFhN01NM2nfbuvXwCbtU5d+XYUtgTP/eNEoQI1ZdzSsbVEPS5QYL4FpaipPxxOSDaMjKk9V9aZsMdOH3PZpVg9p3f5nuw2DyIQoaljxSAiwGxo0+gFzAMx09ikQKq/EaCnjtPhQjtTqeoJF7M5KsQjxYKEBDybH+7pmSHS7vZ0Bot+z29QT53Hbzzkd6cT6lPIovupfBCN64LaqiKCNbQG5B8TEwVuFL
    RABBITMQ_DEFAULT_USER: AgCBxfeiiHF6ukMUsbidWB0OvOuOHg7Xf/2mm1KQJCg9Ui3gXCKzsBUIw75JQJzVdoZ4eTkPGQ8r+sPbJtvll7cFumXJeFA3o0yZ8d5YT7tztrPOlmEUR1n49gGMev9Z99Cwuc4EcUuow2wuszhOVe/F82ds2dwA50tw7PFr+NrEpzJoVii2OEk3mbqB4oTdWrm1tL4ZdDQeHXeChkmHRVei+Xw8PxjkWjHHKIJdnGgQjtWM8kZAJsuvOMyv92OkyXGZtxT/t7+Sogx9rGIo3SA0fhLbJ7bvF6NEWv7r5Io6PNHmFjVJHwQNHJwT0XkSsAUu/Elm87mZBg5cTgyT0A3fkWFzRonnJ7jXwap0ZVXzZYZRWo9ElQf1kpmdFEMw1+piKV295R4kBESd0dqzFSHB4EhU7Y7pDgOyJ7YzJnsi43TxVxsNpV4GiAVkYhHVBowZnL2fJPVpWPJ5iocyTcMQAn48FJvGY+SOtv+dfS2a17JRr1kWWmAXacYuhMwlZSodPBUH7o8L+pr3JIbDNzpiAT/HrALHCeXYjQaDyu/JM77itrYtMY2SMxZbbXDpPmCTCg/yqGOBUiDwHLzsIhCtXdFZ8u/0lkUGlFMpluDHMP9lfKpXPysFAPuI/SVk2O9uL0qvD6niUpat/8Ix5yA0OFPz0kxppvyztdTEePpIyPxIAji8w1no4L1xohXUiwKYch16HqtaxUo=
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: opslora-app-ns
    type: Opaque
